import cv2
from time import sleep
import datetime
import os
import pyttsx3
from dhooks import Webhook, File

#HERE YOU MUST TO WRITE YOUR CODE GENERATED BY DISCORD
hook = Webhook("https://discord.com/api/webhooks/123564988789451651")  

# transforma texto a voz
def hablar(engine):
    try:       
        engine.say("First and last advice, mi boss know you are in his room.")
        engine.runAndWait()
    except:
            pass


#PARAMETER USED BY THE VOICE
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
engine.setProperty('rate', 150)


lista_estados=[None,None]
imagen_inicial=None
video=cv2.VideoCapture(0)


while True:
    check, frame = video.read()
    estado=0
    gray_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray_frame=cv2.GaussianBlur(gray_frame,(25,25),2)
    if imagen_inicial is None:
        imagen_inicial=gray_frame
        continue

    delta=cv2.absdiff(imagen_inicial,gray_frame)
    threshold=cv2.threshold(delta, 30, 255, cv2.THRESH_BINARY)[1]
    (contornos,_)=cv2.findContours(threshold,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[-2:]

    for contorno in contornos:
        if cv2.contourArea(contorno) < 10000:
            continue
        estado=1
        (x, y, w, h)=cv2.boundingRect(contorno)
        #cv2.rectangle(frame, (x, y), (x+w, y+h), (0,255,0), 1)
    lista_estados.append(estado)

    if lista_estados[-1]==1 and lista_estados[-2]==0:        

        name=str(datetime.datetime.now())
        name = name.replace(":", "")
        name = name.replace(".", "_")+ '.jpg'
        
        cv2.imwrite("img\\"+ name,frame)

        data= "MASTER, THERE IS AN INTRUDER IN YOUR KINGDOM"
        pict= File("img\\" + name)
        hook.send(data)
        hook.send("Evidence", file = pict)

        hablar(engine)
        sleep(0.1)
  

    #cv2.imshow("gray_frame Frame",gray_frame)
    #cv2.imshow("Delta Frame",delta)
    #cv2.imshow("Threshold Frame",threshold)
    cv2.imshow("Color Frame",frame)
    
    if cv2.waitKey(1)==ord('q'):
        break

#FREE THE RESOURCES
video.release()
cv2.destroyAllWindows